version: '3.8'
services:

  chromedriver:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"
    shm_size: '512M'  
    tmpfs:
      - /dev/shm

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'

  app:
    build: ./backend
    container_name: app
    volumes:
      - ./backend:/backend
    depends_on:
      - chromedriver
      - pgdb
      - redis

volumes:
  pgdata: